POST http://localhost:3001/api/blogs
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pZXR0aW8xIiwiaWQiOiI2NmM4OWE4YTUxMWI1YTI4NGY4NTMyOTUiLCJpYXQiOjE3MjQ1ODI5NjYsImV4cCI6MTcyNDU4NjU2Nn0.0_e6-bZP9ZXsoqcP7RcxcTj-ArMMGMbfT-7_BQm2-kc

{
    "title": "Onnin uusin blogi userExtractorin jälkeen",
    "author": "Onni Miettinen",
    "url": "http://localhost:3001/api/users",
    "likes": 1
}