DELETE http://localhost:3001/api/blogs/66c8a4b8d50d30ed288d3313
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pZXR0aW8xIiwiaWQiOiI2NmM4OWE4YTUxMWI1YTI4NGY4NTMyOTUiLCJpYXQiOjE3MjQ1ODA2MzEsImV4cCI6MTcyNDU4NDIzMX0.Mzs4CD0CsoDHkJ7cYIBOioThdTpuM76PEjRnk7vARYw